### ISSUE TITLE
关于res_pack的使用问题

### ISSUE THREAD

**Issue by MDCY9008** [hzyitc/AmlImg#1]
本人想把armbian的```boot```分区打包成img，使用res_pack打包需要```list.txt```文件，想请教一下这个```list.txt```怎么编写才能打包全部文件。

**Comment by hzyitc** [comment]
应该是`pack`命令，这才是打包成刷机镜像。`res_pack`命令用于打包资源文件的。

具体流程可参考[`hzyitc/u-boot-onecloud`的`build.yml`](https://github.com/hzyitc/u-boot-onecloud/blob/onecloud/.github/workflows/build.yml)。

或者使用`unpack`命令解包一个刷机镜像，进行观察。

**Comment by MDCY9008** [comment]
> 应该是`pack`命令，这才是打包成刷机镜像。`res_pack`命令用于打包资源文件的。
> 
> 具体流程可参考[`hzyitc/u-boot-onecloud`的`build.yml`](https://github.com/hzyitc/u-boot-onecloud/blob/onecloud/.github/workflows/build.yml)。
> 
> 或者使用`unpack`命令解包一个刷机镜像，进行观察。

这个我研究过，unpack了release里的emmc_burn.img，如果要制作armbian的还需要boot.img和rootfs.img，所以说这两个img不能通过这个工具打包，是这样理解吗。

**Comment by hzyitc** [comment]
`res_pack` 是用于把资源打包成amlogic专有格式的镜像文件的，其本质上也是文件系统。

这些其实都是`分区镜像文件`，你输入什么数据，他就直接在硬盘写入什么数据。相当于`dd`命令。

**Comment by hzyitc** [comment]
其实Windows下你直接用`7-zip`打开`硬盘镜像文件`出来的直接就是`分区镜像文件`。

Linux下用`loop`挂载，直接`dd`下`loopXpY`出来的也是`分区镜像文件`
